"""
Project MIDAS v2 — Backtester
Backtesting engine with basic risk management baked in from Day 1.

Supports:
  - Single strategy testing
  - Multi-strategy combined testing (voting engine)
  - Train/forward test split
  - Walk-forward validation (for AI training later)
  - Full metrics reporting (Sharpe, PF, MaxDD, etc.)

Risk baked in:
  - SL on every trade (strategy-defined)
  - Fixed lot sizing (0.01 single, 0.02 multi-agree)
  - Max $40/trade risk
  - Session limits (2 per session)
  - $100/day loss cap
  - Spread/slippage simulation

Usage:
    bt = Backtester()
    results = bt.run(df_m15, df_m5, strategy, mode="backtest")
    bt.print_report(results)
    bt.plot_equity(results)
"""

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Optional, Dict

import numpy as np
import pandas as pd

from config import (
    BACKTEST_INITIAL_CAPITAL, MAX_DAILY_LOSS, MAX_TRADE_RISK,
    LOT_SIZE_SINGLE, LOT_SIZE_MULTI, SESSION_LIMITS,
    SPREAD_SIMULATION_PIPS, PIP_VALUE, XAUUSD_POINT_VALUE,
    COOLDOWN_SECONDS, CONFIDENCE_THRESHOLD,
    BACKTEST_TRAIN_END, BACKTEST_FORWARD_START,
    BACKTEST_DIR
)


# ─── Data Classes ────────────────────────────────────────

@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    datetime: datetime
    direction: str              # "buy" or "sell"
    strategy_name: str
    confidence: float           # 0-100
    sl_price: float             # Strategy-defined stop loss
    tp_price: float             # Strategy-defined take profit
    entry_price: float          # Intended entry price
    sub_conditions: Dict = field(default_factory=dict)  # e.g., {"BOS": True, "OB": True}


@dataclass
class Trade:
    """A completed trade with full details."""
    entry_time: datetime
    exit_time: datetime
    direction: str
    strategy_name: str
    confidence: float
    entry_price: float
    exit_price: float
    sl_price: float
    tp_price: float
    lot_size: float
    pnl_dollars: float
    pnl_pips: float
    exit_reason: str            # "tp_hit", "sl_hit", "daily_limit", "session_end"
    session: str
    sub_conditions: Dict = field(default_factory=dict)
    rr_achieved: float = 0.0   # Risk-reward actually achieved


@dataclass
class DailyState:
    """Tracks daily trading state for risk management."""
    date: str
    pnl: float = 0.0
    trades_taken: int = 0
    session_trades: Dict = field(default_factory=lambda: {
        "asian": 0, "london": 0, "new_york": 0, "london_ny_overlap": 0, "off": 0
    })
    is_locked: bool = False     # Daily loss limit hit


# ─── Backtester ──────────────────────────────────────────

class Backtester:
    """
    Event-driven backtester with built-in risk management.
    
    Processes candles sequentially, respecting time ordering.
    No lookahead bias — each decision uses only past data.
    """

    def __init__(self, initial_capital: float = None, verbose: bool = True):
        self.initial_capital = initial_capital or BACKTEST_INITIAL_CAPITAL
        self.verbose = verbose

    def run(
        self,
        df: pd.DataFrame,
        strategy,
        mode: str = "full",
        lot_override: float = None,
    ) -> Dict:
        """
        Run backtest on a single strategy.

        Args:
            df: Feature-engineered DataFrame (must have shared features computed).
                Should be the ENTRY timeframe (e.g., M5) with M15 features merged.
            strategy: Strategy object with .generate_signals(df, idx) method
            mode: "backtest" (train period), "forward" (test period), "full" (all data)
            lot_override: Override lot size (useful for testing)

        Returns:
            Dict with trades, equity curve, metrics, and daily states
        """
        # Filter by mode
        df = self._filter_by_mode(df, mode)
        if len(df) == 0:
            print(f"WARNING: No data for mode='{mode}'")
            return self._empty_results()

        # Initialize state
        capital = self.initial_capital
        equity_curve = [capital]
        equity_times = [df["datetime"].iloc[0]]
        trades: List[Trade] = []
        daily_states: Dict[str, DailyState] = {}

        # Track active position
        active_trade = None
        last_trade_time = None

        if self.verbose:
            print(f"\n{'='*60}")
            print(f"Backtesting: {strategy.name}")
            print(f"Mode: {mode}")
            print(f"Period: {df['datetime'].iloc[0]} to {df['datetime'].iloc[-1]}")
            print(f"Candles: {len(df):,}")
            print(f"Initial capital: ${self.initial_capital:,.2f}")
            print(f"{'='*60}\n")

        # Main loop — process each candle
        for idx in range(len(df)):
            row = df.iloc[idx]
            current_time = row["datetime"]
            current_date = current_time.strftime("%Y-%m-%d")

            # Initialize daily state
            if current_date not in daily_states:
                daily_states[current_date] = DailyState(date=current_date)
            daily = daily_states[current_date]

            # ─── Check if we have an active trade ─────────
            if active_trade is not None:
                exit_result = self._check_exit(active_trade, row)

                if exit_result is not None:
                    exit_price, exit_reason = exit_result

                    # Calculate P&L
                    pnl = self._calculate_pnl(
                        active_trade["direction"],
                        active_trade["entry_price"],
                        exit_price,
                        active_trade["lot_size"]
                    )
                    pnl_pips = self._calculate_pips(
                        active_trade["direction"],
                        active_trade["entry_price"],
                        exit_price
                    )

                    # Calculate RR achieved
                    risk_pips = abs(active_trade["entry_price"] - active_trade["sl_price"]) / PIP_VALUE
                    rr_achieved = pnl_pips / risk_pips if risk_pips > 0 else 0

                    # Record trade
                    trade = Trade(
                        entry_time=active_trade["entry_time"],
                        exit_time=current_time,
                        direction=active_trade["direction"],
                        strategy_name=active_trade["strategy_name"],
                        confidence=active_trade["confidence"],
                        entry_price=active_trade["entry_price"],
                        exit_price=exit_price,
                        sl_price=active_trade["sl_price"],
                        tp_price=active_trade["tp_price"],
                        lot_size=active_trade["lot_size"],
                        pnl_dollars=pnl,
                        pnl_pips=pnl_pips,
                        exit_reason=exit_reason,
                        session=active_trade["session"],
                        sub_conditions=active_trade.get("sub_conditions", {}),
                        rr_achieved=rr_achieved,
                    )
                    trades.append(trade)

                    # Update state
                    capital += pnl
                    daily.pnl += pnl
                    last_trade_time = current_time
                    active_trade = None

                    equity_curve.append(capital)
                    equity_times.append(current_time)

                    # Check if daily loss limit hit
                    if daily.pnl <= -MAX_DAILY_LOSS:
                        daily.is_locked = True

                continue  # Don't open new trade on same candle as exit

            # ─── Check if we can trade ────────────────────
            if daily.is_locked:
                continue

            session = row.get("session", "off")
            session_key = session if session in SESSION_LIMITS else "off"
            if daily.session_trades.get(session_key, 0) >= SESSION_LIMITS.get(session_key, 0):
                continue

            # Cooldown check
            if last_trade_time is not None:
                elapsed = (current_time - last_trade_time).total_seconds()
                if elapsed < COOLDOWN_SECONDS:
                    continue

            # ─── Ask strategy for a signal ────────────────
            signal = strategy.generate_signal(df, idx)

            if signal is None:
                continue

            if signal.confidence < CONFIDENCE_THRESHOLD:
                continue

            # ─── Risk checks ──────────────────────────────
            # Calculate lot size
            lot = lot_override or LOT_SIZE_SINGLE

            # Apply spread/slippage
            entry_price = self._apply_spread(signal.entry_price, signal.direction)

            # Check max trade risk
            sl_distance_dollars = abs(entry_price - signal.sl_price) * lot * XAUUSD_POINT_VALUE
            if sl_distance_dollars > MAX_TRADE_RISK:
                # Reduce lot size to fit within risk limit
                max_lot = MAX_TRADE_RISK / (abs(entry_price - signal.sl_price) * XAUUSD_POINT_VALUE)
                lot = max(0.01, round(max_lot, 2))
                # Recalculate
                sl_distance_dollars = abs(entry_price - signal.sl_price) * lot * XAUUSD_POINT_VALUE
                if sl_distance_dollars > MAX_TRADE_RISK:
                    continue  # Still too risky, skip

            # Check remaining daily budget
            remaining_daily = MAX_DAILY_LOSS + daily.pnl  # How much we can still lose today
            if sl_distance_dollars > remaining_daily:
                continue  # This trade could breach daily limit

            # ─── Open trade ───────────────────────────────
            active_trade = {
                "entry_time": current_time,
                "entry_price": entry_price,
                "direction": signal.direction,
                "sl_price": signal.sl_price,
                "tp_price": signal.tp_price,
                "lot_size": lot,
                "strategy_name": signal.strategy_name,
                "confidence": signal.confidence,
                "session": session,
                "sub_conditions": signal.sub_conditions,
            }

            # Update session count
            daily.session_trades[session_key] = daily.session_trades.get(session_key, 0) + 1
            daily.trades_taken += 1

        # ─── Close any remaining open trade at last candle ──
        if active_trade is not None:
            last_row = df.iloc[-1]
            pnl = self._calculate_pnl(
                active_trade["direction"],
                active_trade["entry_price"],
                last_row["close"],
                active_trade["lot_size"]
            )
            pnl_pips = self._calculate_pips(
                active_trade["direction"],
                active_trade["entry_price"],
                last_row["close"]
            )
            risk_pips = abs(active_trade["entry_price"] - active_trade["sl_price"]) / PIP_VALUE
            trade = Trade(
                entry_time=active_trade["entry_time"],
                exit_time=last_row["datetime"],
                direction=active_trade["direction"],
                strategy_name=active_trade["strategy_name"],
                confidence=active_trade["confidence"],
                entry_price=active_trade["entry_price"],
                exit_price=last_row["close"],
                sl_price=active_trade["sl_price"],
                tp_price=active_trade["tp_price"],
                lot_size=active_trade["lot_size"],
                pnl_dollars=pnl,
                pnl_pips=pnl_pips,
                exit_reason="end_of_data",
                session=active_trade["session"],
                sub_conditions=active_trade.get("sub_conditions", {}),
                rr_achieved=pnl_pips / risk_pips if risk_pips > 0 else 0,
            )
            trades.append(trade)
            capital += pnl
            equity_curve.append(capital)
            equity_times.append(last_row["datetime"])

        # ─── Compute metrics ──────────────────────────────
        metrics = self._compute_metrics(trades, equity_curve)

        results = {
            "strategy": strategy.name,
            "mode": mode,
            "start_date": str(df["datetime"].iloc[0]),
            "end_date": str(df["datetime"].iloc[-1]),
            "initial_capital": self.initial_capital,
            "final_capital": capital,
            "trades": trades,
            "equity_curve": equity_curve,
            "equity_times": equity_times,
            "daily_states": daily_states,
            "metrics": metrics,
        }

        if self.verbose:
            self.print_report(results)

        return results

    # ─── Exit Logic ──────────────────────────────────────

    def _check_exit(self, trade: Dict, row) -> Optional[tuple]:
        """
        Check if active trade should be closed based on current candle.
        Returns (exit_price, exit_reason) or None.

        Checks TP and SL using HIGH and LOW of the candle to simulate
        intra-candle price movement. SL is checked FIRST (conservative).
        """
        high = row["high"]
        low = row["low"]

        if trade["direction"] == "buy":
            # SL hit? (price went below SL)
            if low <= trade["sl_price"]:
                return (trade["sl_price"], "sl_hit")
            # TP hit? (price went above TP)
            if high >= trade["tp_price"]:
                return (trade["tp_price"], "tp_hit")

        elif trade["direction"] == "sell":
            # SL hit? (price went above SL)
            if high >= trade["sl_price"]:
                return (trade["sl_price"], "sl_hit")
            # TP hit? (price went below TP)
            if low <= trade["tp_price"]:
                return (trade["tp_price"], "tp_hit")

        return None

    # ─── P&L Calculations ────────────────────────────────

    def _calculate_pnl(self, direction: str, entry: float, exit: float, lots: float) -> float:
        """Calculate dollar P&L for a trade."""
        if direction == "buy":
            return (exit - entry) * lots * XAUUSD_POINT_VALUE
        else:  # sell
            return (entry - exit) * lots * XAUUSD_POINT_VALUE

    def _calculate_pips(self, direction: str, entry: float, exit: float) -> float:
        """Calculate pip movement."""
        if direction == "buy":
            return (exit - entry) / PIP_VALUE
        else:
            return (entry - exit) / PIP_VALUE

    def _apply_spread(self, price: float, direction: str) -> float:
        """Simulate spread/slippage on entry."""
        spread_dollars = SPREAD_SIMULATION_PIPS * PIP_VALUE
        if direction == "buy":
            return price + spread_dollars  # Worse fill for buy
        else:
            return price - spread_dollars  # Worse fill for sell

    # ─── Data Filtering ──────────────────────────────────

    def _filter_by_mode(self, df: pd.DataFrame, mode: str) -> pd.DataFrame:
        """Filter data by backtest/forward/full mode."""
        if mode == "full":
            return df.copy()

        df = df.copy()
        if not pd.api.types.is_datetime64_any_dtype(df["datetime"]):
            df["datetime"] = pd.to_datetime(df["datetime"])

        if mode == "backtest":
            return df[df["datetime"] <= BACKTEST_TRAIN_END].reset_index(drop=True)
        elif mode == "forward":
            return df[df["datetime"] >= BACKTEST_FORWARD_START].reset_index(drop=True)
        else:
            print(f"WARNING: Unknown mode '{mode}', using full data")
            return df

    # ─── Metrics ─────────────────────────────────────────

    def _compute_metrics(self, trades: List[Trade], equity_curve: List[float]) -> Dict:
        """Compute comprehensive trading metrics."""
        if not trades:
            return self._empty_metrics()

        pnls = [t.pnl_dollars for t in trades]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p <= 0]

        total_pnl = sum(pnls)
        num_trades = len(trades)
        win_rate = len(wins) / num_trades * 100 if num_trades > 0 else 0

        avg_win = np.mean(wins) if wins else 0
        avg_loss = abs(np.mean(losses)) if losses else 0.001

        # Profit Factor
        gross_profit = sum(wins) if wins else 0
        gross_loss = abs(sum(losses)) if losses else 0.001
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

        # Max Drawdown
        peak = equity_curve[0]
        max_dd = 0
        max_dd_pct = 0
        for eq in equity_curve:
            if eq > peak:
                peak = eq
            dd = peak - eq
            dd_pct = dd / peak * 100 if peak > 0 else 0
            max_dd = max(max_dd, dd)
            max_dd_pct = max(max_dd_pct, dd_pct)

        # Consecutive losses
        max_consec_loss = 0
        current_streak = 0
        for p in pnls:
            if p <= 0:
                current_streak += 1
                max_consec_loss = max(max_consec_loss, current_streak)
            else:
                current_streak = 0

        # Monthly breakdown
        monthly_pnl = {}
        for t in trades:
            month_key = t.entry_time.strftime("%Y-%m") if isinstance(t.entry_time, datetime) else str(t.entry_time)[:7]
            monthly_pnl[month_key] = monthly_pnl.get(month_key, 0) + t.pnl_dollars

        profitable_months = sum(1 for v in monthly_pnl.values() if v > 0)
        total_months = len(monthly_pnl) if monthly_pnl else 1
        monthly_win_pct = profitable_months / total_months * 100

        # Sharpe Ratio (annualized, assuming ~252 trading days)
        if len(pnls) > 1:
            daily_returns = pd.Series(pnls)
            sharpe = (daily_returns.mean() / daily_returns.std()) * np.sqrt(252) if daily_returns.std() > 0 else 0
        else:
            sharpe = 0

        # Avg RR
        rr_values = [t.rr_achieved for t in trades if t.rr_achieved != 0]
        avg_rr = np.mean(rr_values) if rr_values else 0

        # Trades per month
        if trades:
            first_trade = trades[0].entry_time
            last_trade = trades[-1].entry_time
            if isinstance(first_trade, str):
                first_trade = pd.to_datetime(first_trade)
                last_trade = pd.to_datetime(last_trade)
            duration_months = max(1, (last_trade - first_trade).days / 30.44)
            trades_per_month = num_trades / duration_months
        else:
            trades_per_month = 0

        # Session breakdown
        session_stats = {}
        for t in trades:
            s = t.session
            if s not in session_stats:
                session_stats[s] = {"trades": 0, "pnl": 0, "wins": 0}
            session_stats[s]["trades"] += 1
            session_stats[s]["pnl"] += t.pnl_dollars
            if t.pnl_dollars > 0:
                session_stats[s]["wins"] += 1

        # Exit reason breakdown
        exit_reasons = {}
        for t in trades:
            r = t.exit_reason
            exit_reasons[r] = exit_reasons.get(r, 0) + 1

        return {
            "total_pnl": round(total_pnl, 2),
            "total_return_pct": round(total_pnl / self.initial_capital * 100, 2),
            "num_trades": num_trades,
            "win_rate": round(win_rate, 2),
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "avg_win_loss_ratio": round(avg_win / avg_loss if avg_loss > 0 else 0, 2),
            "profit_factor": round(profit_factor, 2),
            "sharpe_ratio": round(sharpe, 2),
            "max_drawdown_dollars": round(max_dd, 2),
            "max_drawdown_pct": round(max_dd_pct, 2),
            "max_consecutive_losses": max_consec_loss,
            "trades_per_month": round(trades_per_month, 1),
            "profitable_months_pct": round(monthly_win_pct, 1),
            "avg_rr_achieved": round(avg_rr, 2),
            "monthly_pnl": {k: round(v, 2) for k, v in monthly_pnl.items()},
            "session_stats": session_stats,
            "exit_reasons": exit_reasons,
        }

    def _empty_metrics(self) -> Dict:
        return {
            "total_pnl": 0, "total_return_pct": 0, "num_trades": 0,
            "win_rate": 0, "avg_win": 0, "avg_loss": 0,
            "avg_win_loss_ratio": 0, "profit_factor": 0, "sharpe_ratio": 0,
            "max_drawdown_dollars": 0, "max_drawdown_pct": 0,
            "max_consecutive_losses": 0, "trades_per_month": 0,
            "profitable_months_pct": 0, "avg_rr_achieved": 0,
            "monthly_pnl": {}, "session_stats": {}, "exit_reasons": {},
        }

    def _empty_results(self) -> Dict:
        return {
            "strategy": "unknown", "mode": "unknown",
            "trades": [], "equity_curve": [self.initial_capital],
            "equity_times": [], "daily_states": {},
            "metrics": self._empty_metrics(),
        }

    # ─── Reporting ───────────────────────────────────────

    def print_report(self, results: Dict):
        """Print a formatted report of backtest results."""
        m = results["metrics"]
        print(f"\n{'='*60}")
        print(f"  BACKTEST REPORT: {results['strategy']}")
        print(f"  Mode: {results['mode']}")
        print(f"  Period: {results.get('start_date', 'N/A')} to {results.get('end_date', 'N/A')}")
        print(f"{'='*60}")

        print(f"\n  {'PERFORMANCE':}")
        print(f"  Total P&L:              ${m['total_pnl']:>10,.2f} ({m['total_return_pct']:+.2f}%)")
        print(f"  Final Capital:          ${results.get('final_capital', 0):>10,.2f}")
        print(f"  Profit Factor:          {m['profit_factor']:>10.2f}")
        print(f"  Sharpe Ratio:           {m['sharpe_ratio']:>10.2f}")

        print(f"\n  {'TRADES':}")
        print(f"  Total Trades:           {m['num_trades']:>10}")
        print(f"  Win Rate:               {m['win_rate']:>9.1f}%")
        print(f"  Avg Win:                ${m['avg_win']:>10.2f}")
        print(f"  Avg Loss:               ${m['avg_loss']:>10.2f}")
        print(f"  Avg Win/Loss Ratio:     {m['avg_win_loss_ratio']:>10.2f}")
        print(f"  Avg RR Achieved:        {m['avg_rr_achieved']:>10.2f}")
        print(f"  Trades/Month:           {m['trades_per_month']:>10.1f}")

        print(f"\n  {'RISK':}")
        print(f"  Max Drawdown:           ${m['max_drawdown_dollars']:>10.2f} ({m['max_drawdown_pct']:.1f}%)")
        print(f"  Max Consecutive Losses: {m['max_consecutive_losses']:>10}")
        print(f"  Profitable Months:      {m['profitable_months_pct']:>9.1f}%")

        # Validation check
        print(f"\n  {'VALIDATION CHECK':}")
        checks = [
            ("Win Rate > 50%", m["win_rate"] > 50),
            ("Profit Factor > 1.5", m["profit_factor"] > 1.5),
            ("Max Drawdown < 8%", m["max_drawdown_pct"] < 8),
            ("Avg Win/Loss > 1.2", m["avg_win_loss_ratio"] > 1.2),
            ("Total PnL Positive", m["total_pnl"] > 0),
            ("Max Consec Losses < 6", m["max_consecutive_losses"] < 6),
            ("Profitable Months > 60%", m["profitable_months_pct"] > 60),
            ("Trades/Month > 15", m["trades_per_month"] > 15),
        ]
        passed = 0
        for label, ok in checks:
            status = "PASS ✅" if ok else "FAIL ❌"
            print(f"    {label:<30} {status}")
            if ok:
                passed += 1

        print(f"\n  Score: {passed}/{len(checks)} checks passed")

        # Session breakdown
        if m["session_stats"]:
            print(f"\n  {'SESSION BREAKDOWN':}")
            for session, stats in m["session_stats"].items():
                wr = stats["wins"] / stats["trades"] * 100 if stats["trades"] > 0 else 0
                print(f"    {session:<20} Trades: {stats['trades']:<5} "
                      f"WR: {wr:.0f}%  PnL: ${stats['pnl']:.2f}")

        # Exit reasons
        if m["exit_reasons"]:
            print(f"\n  {'EXIT REASONS':}")
            for reason, count in m["exit_reasons"].items():
                print(f"    {reason:<20} {count}")

        print(f"\n{'='*60}\n")

    def save_results(self, results: Dict, filename: str = None):
        """Save backtest results to JSON."""
        if filename is None:
            filename = f"{results['strategy']}_{results['mode']}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

        filepath = BACKTEST_DIR / filename

        # Convert trades to serializable format
        save_data = {
            "strategy": results["strategy"],
            "mode": results["mode"],
            "start_date": results.get("start_date"),
            "end_date": results.get("end_date"),
            "initial_capital": results.get("initial_capital"),
            "final_capital": results.get("final_capital"),
            "metrics": results["metrics"],
            "num_trades": len(results["trades"]),
            "trades": [asdict(t) for t in results["trades"]],
        }

        # Convert non-serializable types
        def convert_dt(obj):
            if isinstance(obj, (datetime, pd.Timestamp)):
                return str(obj)
            if isinstance(obj, (np.integer,)):
                return int(obj)
            if isinstance(obj, (np.floating,)):
                return float(obj)
            if isinstance(obj, (np.bool_,)):
                return bool(obj)
            return str(obj)

        with open(filepath, "w") as f:
            json.dump(save_data, f, indent=2, default=convert_dt)

        print(f"Results saved to: {filepath}")

    def plot_equity(self, results: Dict, save_path: str = None):
        """Plot equity curve. Requires matplotlib."""
        try:
            import matplotlib.pyplot as plt
            import matplotlib.dates as mdates
        except ImportError:
            print("matplotlib not installed. Run: pip install matplotlib")
            return

        fig, axes = plt.subplots(2, 1, figsize=(14, 8), gridspec_kw={"height_ratios": [3, 1]})

        # Equity curve
        ax1 = axes[0]
        times = results["equity_times"]
        equity = results["equity_curve"]

        # Ensure same length
        min_len = min(len(times), len(equity))
        times = times[:min_len]
        equity = equity[:min_len]

        ax1.plot(times, equity, color="#2E86C1", linewidth=1.5)
        ax1.axhline(y=self.initial_capital, color="gray", linestyle="--", alpha=0.5)
        ax1.fill_between(times, self.initial_capital, equity,
                         where=[e >= self.initial_capital for e in equity],
                         alpha=0.15, color="green")
        ax1.fill_between(times, self.initial_capital, equity,
                         where=[e < self.initial_capital for e in equity],
                         alpha=0.15, color="red")

        ax1.set_title(f"Equity Curve — {results['strategy']} ({results['mode']})",
                       fontsize=14, fontweight="bold")
        ax1.set_ylabel("Capital ($)")
        ax1.grid(True, alpha=0.3)

        m = results["metrics"]
        info_text = (f"PnL: ${m['total_pnl']:+,.2f} | "
                     f"WR: {m['win_rate']:.1f}% | "
                     f"PF: {m['profit_factor']:.2f} | "
                     f"MaxDD: {m['max_drawdown_pct']:.1f}% | "
                     f"Trades: {m['num_trades']}")
        ax1.text(0.02, 0.02, info_text, transform=ax1.transAxes,
                 fontsize=9, verticalalignment="bottom",
                 bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5))

        # Monthly PnL bars
        ax2 = axes[1]
        monthly = m.get("monthly_pnl", {})
        if monthly:
            months = list(monthly.keys())
            values = list(monthly.values())
            colors = ["#27AE60" if v >= 0 else "#C0392B" for v in values]
            ax2.bar(range(len(months)), values, color=colors, alpha=0.7)
            ax2.set_xticks(range(0, len(months), max(1, len(months) // 12)))
            ax2.set_xticklabels(
                [months[i] for i in range(0, len(months), max(1, len(months) // 12))],
                rotation=45, fontsize=8
            )
            ax2.axhline(y=0, color="gray", linewidth=0.5)
            ax2.set_ylabel("Monthly P&L ($)")
            ax2.grid(True, alpha=0.3)

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=150, bbox_inches="tight")
            print(f"Chart saved to: {save_path}")
        else:
            plt.show()

        plt.close()


# ─── Strategy Base Class ─────────────────────────────────

class StrategyBase:
    """
    Base class for all strategies.
    Override generate_signal() in subclasses.
    """

    name: str = "BaseStrategy"

    def generate_signal(self, df: pd.DataFrame, idx: int) -> Optional[TradeSignal]:
        """
        Check if there's a trade signal at the given index.

        Args:
            df: Full feature-engineered DataFrame
            idx: Current candle index (only use data up to and including idx)

        Returns:
            TradeSignal if there's a valid signal, None otherwise.
            
        IMPORTANT: Only use df.iloc[:idx+1] to avoid lookahead bias!
        """
        raise NotImplementedError("Subclasses must implement generate_signal()")


# ─── Dummy Strategy for Testing ──────────────────────────

class DummyStrategy(StrategyBase):
    """
    Simple EMA crossover strategy for testing the backtester.
    NOT for production — just validates that the backtester works correctly.
    """

    name = "DummyEMACross"

    def generate_signal(self, df: pd.DataFrame, idx: int) -> Optional[TradeSignal]:
        # Need at least 200 candles for EMA200
        if idx < 200:
            return None

        row = df.iloc[idx]
        prev = df.iloc[idx - 1]

        # Only check once per 5 candles (reduce signal frequency)
        if idx % 5 != 0:
            return None

        atr = row.get(f"atr_14", 2.0)  # Default ATR if not computed

        # Simple: EMA9 crosses above EMA21 = buy, below = sell
        if "ema_9" not in df.columns or "ema_21" not in df.columns:
            return None

        ema9_now = row["ema_9"]
        ema21_now = row["ema_21"]
        ema9_prev = prev["ema_9"]
        ema21_prev = prev["ema_21"]

        signal = None

        # Bullish crossover
        if ema9_prev <= ema21_prev and ema9_now > ema21_now:
            sl = row["close"] - 2 * atr
            tp = row["close"] + 3 * atr
            signal = TradeSignal(
                datetime=row["datetime"],
                direction="buy",
                strategy_name=self.name,
                confidence=70,
                sl_price=sl,
                tp_price=tp,
                entry_price=row["close"],
                sub_conditions={"ema_cross": True, "above_ema200": bool(row.get("above_ema200", 0))},
            )

        # Bearish crossover
        elif ema9_prev >= ema21_prev and ema9_now < ema21_now:
            sl = row["close"] + 2 * atr
            tp = row["close"] - 3 * atr
            signal = TradeSignal(
                datetime=row["datetime"],
                direction="sell",
                strategy_name=self.name,
                confidence=70,
                sl_price=sl,
                tp_price=tp,
                entry_price=row["close"],
                sub_conditions={"ema_cross": True, "above_ema200": bool(row.get("above_ema200", 0))},
            )

        return signal


# ─── Quick Test ──────────────────────────────────────────

if __name__ == "__main__":
    """
    Quick test: run dummy strategy on processed M5 data.
    This validates the backtester works correctly.
    """
    from config import DATA_PROCESSED

    m5_file = DATA_PROCESSED / "XAUUSD_M5_features.csv"

    if not m5_file.exists():
        print(f"Processed M5 data not found at: {m5_file}")
        print("Run feature_engineering.py first to generate processed data.")
        print("\nOr run data_downloader.py first if you haven't downloaded data yet.")
        sys.exit(1)

    import sys
    print("Loading M5 data...")
    df = pd.read_csv(m5_file, parse_dates=["datetime"])
    print(f"Loaded {len(df):,} candles")

    # Run backtest
    bt = Backtester()
    strategy = DummyStrategy()

    print("\n--- BACKTEST (Train Period) ---")
    results_bt = bt.run(df, strategy, mode="backtest")
    bt.save_results(results_bt)

    print("\n--- FORWARD TEST ---")
    results_fw = bt.run(df, strategy, mode="forward")
    bt.save_results(results_fw)

    # Plot if matplotlib available
    try:
        bt.plot_equity(results_bt, save_path=str(BACKTEST_DIR / "dummy_backtest_equity.png"))
        bt.plot_equity(results_fw, save_path=str(BACKTEST_DIR / "dummy_forward_equity.png"))
    except Exception as e:
        print(f"Plotting skipped: {e}")